"""writeoff_documents

Revision ID: c1c2a44669d3
Revises: 0002_schema_squash
Create Date: 2026-08-27 10:46:09.543154

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c1c2a44669d3'
down_revision: Union[str, Sequence[str], None] = '0002_schema_squash'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('writeoff_documents',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('writeoff_date', sa.Date(), nullable=False),
    sa.Column('title', sa.String(length=255), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('created_by', sa.Integer(), nullable=True),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('writeoff_items',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('document_id', sa.Integer(), nullable=False),
    sa.Column('account_id', sa.Integer(), nullable=False),
    sa.Column('services_type_id', sa.Integer(), nullable=False),
    sa.Column('allocated', sa.Numeric(precision=15, scale=2), nullable=False),
    sa.Column('balance_after', sa.Numeric(precision=15, scale=2), nullable=True),
    sa.ForeignKeyConstraint(['account_id'], ['accounts.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['document_id'], ['writeoff_documents.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['services_type_id'], ['services_type.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('accounts_register', sa.Column('writeoff_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'accounts_register', 'writeoff_documents', ['writeoff_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'role',
               existing_type=sa.VARCHAR(length=50),
               type_=sa.Enum('admin', 'operator', 'cashier', 'controller', 'resident', name='userrole', native_enum=False),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'role',
               existing_type=sa.Enum('admin', 'operator', 'cashier', 'controller', 'resident', name='userrole', native_enum=False),
               type_=sa.VARCHAR(length=50),
               existing_nullable=False)
    op.drop_constraint(None, 'accounts_register', type_='foreignkey')
    op.drop_column('accounts_register', 'writeoff_id')
    op.drop_table('writeoff_items')
    op.drop_table('writeoff_documents')
    # ### end Alembic commands ###
