"""document_audit

Revision ID: fce9ed483469
Revises: c1c2a44669d3
Create Date: 2026-08-27 11:13:57.880931

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fce9ed483469'
down_revision: Union[str, Sequence[str], None] = 'c1c2a44669d3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('accrual_documents', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('accrual_documents', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('accrual_documents', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('accrual_documents', sa.Column('change_description', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'accrual_documents', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'accrual_documents', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('meter_reading_documents', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('meter_reading_documents', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('meter_reading_documents', sa.Column('change_description', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'meter_reading_documents', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'meter_reading_documents', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('receipt_documents', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('receipt_documents', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('receipt_documents', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('receipt_documents', sa.Column('change_description', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'receipt_documents', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'receipt_documents', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.add_column('transactions', sa.Column('created_by', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('transactions', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('transactions', sa.Column('change_description', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'transactions', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    op.create_foreign_key(None, 'transactions', 'users', ['created_by'], ['id'], ondelete='SET NULL')
    op.add_column('writeoff_documents', sa.Column('updated_by', sa.Integer(), nullable=True))
    op.add_column('writeoff_documents', sa.Column('updated_at', sa.TIMESTAMP(), server_default=sa.text('now()'), nullable=True))
    op.add_column('writeoff_documents', sa.Column('change_description', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'writeoff_documents', 'users', ['updated_by'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'writeoff_documents', type_='foreignkey')
    op.drop_column('writeoff_documents', 'change_description')
    op.drop_column('writeoff_documents', 'updated_at')
    op.drop_column('writeoff_documents', 'updated_by')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_constraint(None, 'transactions', type_='foreignkey')
    op.drop_column('transactions', 'change_description')
    op.drop_column('transactions', 'updated_at')
    op.drop_column('transactions', 'updated_by')
    op.drop_column('transactions', 'created_by')
    op.drop_constraint(None, 'receipt_documents', type_='foreignkey')
    op.drop_constraint(None, 'receipt_documents', type_='foreignkey')
    op.drop_column('receipt_documents', 'change_description')
    op.drop_column('receipt_documents', 'updated_at')
    op.drop_column('receipt_documents', 'updated_by')
    op.drop_column('receipt_documents', 'created_by')
    op.drop_constraint(None, 'meter_reading_documents', type_='foreignkey')
    op.drop_constraint(None, 'meter_reading_documents', type_='foreignkey')
    op.drop_column('meter_reading_documents', 'change_description')
    op.drop_column('meter_reading_documents', 'updated_by')
    op.drop_column('meter_reading_documents', 'created_by')
    op.drop_constraint(None, 'accrual_documents', type_='foreignkey')
    op.drop_constraint(None, 'accrual_documents', type_='foreignkey')
    op.drop_column('accrual_documents', 'change_description')
    op.drop_column('accrual_documents', 'updated_at')
    op.drop_column('accrual_documents', 'updated_by')
    op.drop_column('accrual_documents', 'created_by')
    # ### end Alembic commands ###
